# Reposta NGL em vibração livre não amortecida

## Definição do problema

As equações de movimento para um sistema em vibração livre não amortecida são

$$ \boldsymbol{m}  \boldsymbol{\ddot x} + \boldsymbol{k} \boldsymbol{x} = \boldsymbol{0},$$

sujeitas à condições iniciais $\boldsymbol{x}(0)$ e $\boldsymbol{\dot x}(0)$.

### Frequências naturais e modos normais
Substituindo uma solução  da forma $\boldsymbol{x}(t) = \boldsymbol{X} \cos(\omega t + \phi)$ na equação de movimento, ficamos com

$$ \left( -\omega^2 \boldsymbol{m}  +  \boldsymbol{k} \right)\boldsymbol{X} = \boldsymbol{0},$$

que pode ser reescrito para

$$  \omega^2 \boldsymbol{m}\boldsymbol{X}  =  \boldsymbol{k} \boldsymbol{X},$$

prémultiplicando ambos os lados pela inversa da matriz de massa, ficamos com

$$  \omega^2 \boldsymbol{X}  =  \boldsymbol{k} \boldsymbol{X},$$

e fazendo $\boldsymbol{\hat k} = \boldsymbol{k}$ e $\lambda = \omega^2$, ficamos com

$$  \lambda \boldsymbol{X}  =  \boldsymbol{\hat k} \boldsymbol{X}.$$

Fica claro que os quadrados das frequências naturais são os autovalores da matriz $\boldsymbol{\hat k}$ e os modos normais seus autovetores.

Após o cálculo dos modos normais vamos normalizá-los pela atriz de massa, de modo que para $i\ne j$ temos
$$  \boldsymbol{X}_i^T  \boldsymbol{m}  \boldsymbol{X}_i = 1, \quad 
    \boldsymbol{X}_i^T  \boldsymbol{m}  \boldsymbol{X}_j = 0, \quad
    \boldsymbol{X}_i^T  \boldsymbol{k}  \boldsymbol{X}_i = \omega_i^2, \quad 
    \boldsymbol{X}_i^T  \boldsymbol{k}  \boldsymbol{X}_j = 0.$$

### Resposta total

Como, em princípio, encontraremos $N$ frequências naturais e $N$ modos normais correspondentes, a resposta total é da forma

$$\boldsymbol{x}(t) = \sum_{i}^{N} \boldsymbol{X}_i A_i \cos(\omega_i t + \phi_i).$$

Introduzindo as condições iniciais para o deslocamento, para $t = 0$, ficamos com

$$\boldsymbol{x}(0) = \sum_{i}^{N} \boldsymbol{X}_i A_i \cos( \phi_i), $$

onde $\boldsymbol{X}_i$ e $\boldsymbol{x}(0)$ são conhecidos. O sistema acima pode ser reescrito como 

$$  \boldsymbol{X}_m \boldsymbol{A}_{c}  = \boldsymbol{x}(0) ,$$

onde $\boldsymbol{X}_m$ é matriz modal, com a coluna $i$ sendo o modo normal $i$, e $\boldsymbol{A}_{c}$ é uma matriz coluna onde a linha $i$ é $A_i\cos\phi_i$, que são as incógnitas deste sistema.

A equação para velocidades é obtida derivando em relação ao tempo as equações para o deslocalmento.

$$ \boldsymbol{\dot x}(t) = -  \sum_{i}^{N} \boldsymbol{X}_i \omega_iA_i \sin(\omega_i t + \phi_i).$$

Introduzindo as condições iniciais para a velocidade, ficamos com

$$ \boldsymbol{\dot x}(0) = -  \sum_{i}^{N} \boldsymbol{X}_i \omega_iA_i \sin( \phi_i), $$

onde $\boldsymbol{X}_i$, $\omega_i$ e $\boldsymbol{\dot x}(0)$ são conhecidos. Vamos rearrumar o sistema como acima,

$$  \boldsymbol{X}_\omega \boldsymbol{A}_{s}  = -\boldsymbol{\dot x}(0) ,$$

onde $\boldsymbol{X}_\omega$ é uma matriz onde a coluna $i$ é dada por $\omega_i \boldsymbol{X}_i$ e $\boldsymbol{A}_{s}$ é uma matriz coluna onde a linha $i$ é $A_i\sin\phi_i$, que são as incógnitas deste sistema.

Após resolver estes sistemas, calculamos 
$$ A_i = \sqrt{A_i\sin\phi_i^2+A_i\sin\phi_i^2}, \quad \phi_i = \arctan\left(\frac{A_i \sin\phi_i}{A_i \cos\phi_i}\right).$$


## Setup

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as ipw

## Sistema mecânico

O sistema mecânico é definido através das matrizes de massa e rigidez, e dos deslocamentos e velocidades iniciais.

Este notebook, em princípio, vale para qualquer sistema com $N$ graus de liberdade, mas a plotagem só está configurada para até 10 graus de liberdade.

In [23]:
# Make sure all of these are compatible.

m = np.array([[1.0, 0.0, 0.0],
              [0.0, 1.0, 0.0],
              [0.0, 0.0, 1.0]], dtype=np.float64)

k = np.array([[ 2.0, -1.0,  0.0],
              [-1.0,  2.0, -1.0],
              [ 0.0, -1.0,  1.0]], dtype=np.float64)

# Initial displacement
x0 = np.array([0.7369, 0.3279, -0.5910])

# Initial velocity
v0 = np.array([0.0, 0.0, 0.0])

## Frequências naturais e modos normais

In [24]:
k_hat = np.linalg.inv(m)@k
λ, X = np.linalg.eig(k_hat)
ω = np.sqrt(λ)
perm = np.argsort(ω)     # reordering index
ω = ω[perm]
X[...] = X[:, perm]      # modal matrix
display(ω)
display(X)

array([0.44504187, 1.2469796 , 1.80193774])

array([[ 0.32798528, -0.73697623, -0.59100905],
       [ 0.59100905, -0.32798528,  0.73697623],
       [ 0.73697623,  0.59100905, -0.32798528]])

### Normalização

In [25]:
XmX = X.T@m@X
Mii = np.diag(XmX)
#display(Mii)
Xm = X/np.sqrt(Mii)    # Divide colum i by sqrt(Mii). Understand roadcast rules.
#display(Xm.T@m@Xm)

## Sistemas de equações

### Resolvendo para $A_i \cos \phi_i$

In [26]:
Ac = np.linalg.solve(Xm, x0)
display(Ac)

array([-6.87333251e-05, -9.99910503e-01, -2.07632574e-05])

### Resolvendo para $A_i \sin \phi_i$

In [27]:
As = np.linalg.solve(Xm*ω, -v0)

### Cálculo de $A_i$ e $\phi_i$

In [28]:
A = np.hypot(Ac, As)
ϕ = np.arctan2(As, Ac)
display(A)
display(ϕ)

array([6.87333251e-05, 9.99910503e-01, 2.07632574e-05])

array([ 3.14159265, -3.14159265,  3.14159265])

## Resposta total

In [29]:
τ = 2*np.pi/ω[0]
nτ = 5
npτ = 100
times = np.linspace(0, nτ*τ, nτ*npτ)

In [30]:
Acωtϕ = A[:, np.newaxis]*np.cos(ω[:, np.newaxis]*times[np.newaxis,:] + ϕ[:, np.newaxis])

In [31]:
N = Xm.shape[0]
xt = np.zeros(Acωtϕ.shape, dtype=np.float64)
for i in range(N):
    xt += Xm[:,i].reshape(N,1)*Acωtϕ[i,:]

In [32]:
modes = range(1, min(N, 10)+1)
vxs = {f'x{i}' : ipw.Checkbox(value=True,description=f'$x_{i}$', disabled=False, indent=False) 
            for i in modes}
title = ipw.HTML('<h1> Resposta total</h1><p> Escolha os modos para visualizar abaixo.</p>')

def make_plot(**args):
    fig, ax = plt.subplots(figsize=(12, 8))
    ax.set_title('Deslocamento (m)', fontsize=18)
    ax.set_xlabel('Tempo (s)', fontsize=18)
    ax.set_ylabel('x(t)', fontsize=18)
    lines = [ ax.plot(times, xt[i]) for i, c in enumerate(vxs.values()) if c.value ]
        
plot = ipw.interactive_output(make_plot, vxs)
bar = ipw.HBox(list(vxs.values()))
gui = ipw.VBox([title, bar, plot])
gui